# micromamba env create -f conda_env.yml

name: gemma
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tensorboard
  - numpy
  - transformers
  - tqdm
  - rich
  - prompt_toolkit
  - pygments
  - sentencepiece
  - pip:
      - accelerate
      - bitsandbytes
